Grupo_2/src/java/entidades/pages/RepresentanteController.java
package entidades.pages;

import entidades.Representante;
import entidades.pages.util.JsfUtil;
import entidades.pages.util.JsfUtil.PersistAction;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@Named("representanteController")
@SessionScoped
public class RepresentanteController implements Serializable {

    @EJB
    private entidades.pages.RepresentanteFacade ejbFacade;
    private List<Representante> items = null;
    private Representante selected;

    public RepresentanteController() {
    }

    public Representante getSelected() {
        return selected;
    }

    public void setSelected(Representante selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private RepresentanteFacade getFacade() {
        return ejbFacade;
    }

    public Representante prepareCreate() {
        selected = new Representante();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("RepresentanteCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("RepresentanteUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("RepresentanteDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Representante> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Representante getRepresentante(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<Representante> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Representante> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Representante.class)
    public static class RepresentanteControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            RepresentanteController controller = (RepresentanteController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "representanteController");
            return controller.getRepresentante(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Representante) {
                Representante o = (Representante) object;
                return getStringKey(o.getIdRepresentante());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Representante.class.getName()});
                return null;
            }
        }

    }

}

Grupo_2/web/representante/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="RepresentanteCreateDlg" widgetVar="RepresentanteCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateRepresentanteTitle}">
            <h:form id="RepresentanteCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{representanteController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateRepresentanteLabel_idRepresentante}" for="idRepresentante" />
                        <p:inputText id="idRepresentante" value="#{representanteController.selected.idRepresentante}" title="#{bundle.CreateRepresentanteTitle_idRepresentante}" required="true" requiredMessage="#{bundle.CreateRepresentanteRequiredMessage_idRepresentante}"/>
                        <p:outputLabel value="#{bundle.CreateRepresentanteLabel_nombresRepres}" for="nombresRepres" />
                        <p:inputText id="nombresRepres" value="#{representanteController.selected.nombresRepres}" title="#{bundle.CreateRepresentanteTitle_nombresRepres}" required="true" requiredMessage="#{bundle.CreateRepresentanteRequiredMessage_nombresRepres}"/>
                        <p:outputLabel value="#{bundle.CreateRepresentanteLabel_apellidosRepres}" for="apellidosRepres" />
                        <p:inputText id="apellidosRepres" value="#{representanteController.selected.apellidosRepres}" title="#{bundle.CreateRepresentanteTitle_apellidosRepres}" required="true" requiredMessage="#{bundle.CreateRepresentanteRequiredMessage_apellidosRepres}"/>
                        <p:outputLabel value="#{bundle.CreateRepresentanteLabel_edadRepres}" for="edadRepres" />
                        <p:inputText id="edadRepres" value="#{representanteController.selected.edadRepres}" title="#{bundle.CreateRepresentanteTitle_edadRepres}" required="true" requiredMessage="#{bundle.CreateRepresentanteRequiredMessage_edadRepres}"/>
                        <p:outputLabel value="#{bundle.CreateRepresentanteLabel_parentesco}" for="parentesco" />
                        <p:inputText id="parentesco" value="#{representanteController.selected.parentesco}" title="#{bundle.CreateRepresentanteTitle_parentesco}" required="true" requiredMessage="#{bundle.CreateRepresentanteRequiredMessage_parentesco}"/>
                        <p:outputLabel value="#{bundle.CreateRepresentanteLabel_telefono}" for="telefono" />
                        <p:inputText id="telefono" value="#{representanteController.selected.telefono}" title="#{bundle.CreateRepresentanteTitle_telefono}" required="true" requiredMessage="#{bundle.CreateRepresentanteRequiredMessage_telefono}"/>
                        <p:outputLabel value="#{bundle.CreateRepresentanteLabel_idAlumno}" for="idAlumno" />
                        <p:selectOneMenu id="idAlumno" value="#{representanteController.selected.idAlumno}" >
                            <f:selectItems value="#{alumnoController.itemsAvailableSelectOne}"
                                           var="idAlumnoItem"
                                           itemValue="#{idAlumnoItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{representanteController.create}" value="#{bundle.Save}" update="display,:RepresentanteListForm:datalist,:growl" oncomplete="handleSubmit(args,'RepresentanteCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="RepresentanteCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

Grupo_2/web/representante/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="RepresentanteEditDlg" widgetVar="RepresentanteEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditRepresentanteTitle}">
            <h:form id="RepresentanteEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{representanteController.selected != null}">
                        <p:outputLabel value="#{bundle.EditRepresentanteLabel_idRepresentante}" for="idRepresentante" />
                        <p:inputText id="idRepresentante" value="#{representanteController.selected.idRepresentante}" title="#{bundle.EditRepresentanteTitle_idRepresentante}" required="true" requiredMessage="#{bundle.EditRepresentanteRequiredMessage_idRepresentante}"/>
                        <p:outputLabel value="#{bundle.EditRepresentanteLabel_nombresRepres}" for="nombresRepres" />
                        <p:inputText id="nombresRepres" value="#{representanteController.selected.nombresRepres}" title="#{bundle.EditRepresentanteTitle_nombresRepres}" required="true" requiredMessage="#{bundle.EditRepresentanteRequiredMessage_nombresRepres}"/>
                        <p:outputLabel value="#{bundle.EditRepresentanteLabel_apellidosRepres}" for="apellidosRepres" />
                        <p:inputText id="apellidosRepres" value="#{representanteController.selected.apellidosRepres}" title="#{bundle.EditRepresentanteTitle_apellidosRepres}" required="true" requiredMessage="#{bundle.EditRepresentanteRequiredMessage_apellidosRepres}"/>
                        <p:outputLabel value="#{bundle.EditRepresentanteLabel_edadRepres}" for="edadRepres" />
                        <p:inputText id="edadRepres" value="#{representanteController.selected.edadRepres}" title="#{bundle.EditRepresentanteTitle_edadRepres}" required="true" requiredMessage="#{bundle.EditRepresentanteRequiredMessage_edadRepres}"/>
                        <p:outputLabel value="#{bundle.EditRepresentanteLabel_parentesco}" for="parentesco" />
                        <p:inputText id="parentesco" value="#{representanteController.selected.parentesco}" title="#{bundle.EditRepresentanteTitle_parentesco}" required="true" requiredMessage="#{bundle.EditRepresentanteRequiredMessage_parentesco}"/>
                        <p:outputLabel value="#{bundle.EditRepresentanteLabel_telefono}" for="telefono" />
                        <p:inputText id="telefono" value="#{representanteController.selected.telefono}" title="#{bundle.EditRepresentanteTitle_telefono}" required="true" requiredMessage="#{bundle.EditRepresentanteRequiredMessage_telefono}"/>
                        <p:outputLabel value="#{bundle.EditRepresentanteLabel_idAlumno}" for="idAlumno" />
                        <p:selectOneMenu id="idAlumno" value="#{representanteController.selected.idAlumno}" >
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{alumnoController.itemsAvailableSelectOne}"
                                           var="idAlumnoItem"
                                           itemValue="#{idAlumnoItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{representanteController.update}" value="#{bundle.Save}" update="display,:RepresentanteListForm:datalist,:growl" oncomplete="handleSubmit(args, 'RepresentanteEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="RepresentanteEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

Grupo_2/web/representante/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListRepresentanteTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="RepresentanteListForm">
                <p:panel header="#{bundle.ListRepresentanteTitle}">
                    <p:dataTable id="datalist" value="#{representanteController.items}" var="item"
                                 selectionMode="single" selection="#{representanteController.selected}"
                                 paginator="true"
                                 rowKey="#{item.idRepresentante}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListRepresentanteTitle_idRepresentante}"/>
                            </f:facet>
                            <h:outputText value="#{item.idRepresentante}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListRepresentanteTitle_nombresRepres}"/>
                            </f:facet>
                            <h:outputText value="#{item.nombresRepres}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListRepresentanteTitle_apellidosRepres}"/>
                            </f:facet>
                            <h:outputText value="#{item.apellidosRepres}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListRepresentanteTitle_edadRepres}"/>
                            </f:facet>
                            <h:outputText value="#{item.edadRepres}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListRepresentanteTitle_parentesco}"/>
                            </f:facet>
                            <h:outputText value="#{item.parentesco}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListRepresentanteTitle_telefono}"/>
                            </f:facet>
                            <h:outputText value="#{item.telefono}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListRepresentanteTitle_idAlumno}"/>
                            </f:facet>
                            <h:outputText value="#{item.idAlumno}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{representanteController.prepareCreate}" update=":RepresentanteCreateForm" oncomplete="PF('RepresentanteCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":RepresentanteViewForm" oncomplete="PF('RepresentanteViewDialog').show()" disabled="#{empty representanteController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":RepresentanteEditForm" oncomplete="PF('RepresentanteEditDialog').show()" disabled="#{empty representanteController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{representanteController.destroy}" update=":growl,datalist" disabled="#{empty representanteController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

Grupo_2/web/representante/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="RepresentanteViewDlg" widgetVar="RepresentanteViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewRepresentanteTitle}">
            <h:form id="RepresentanteViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{representanteController.selected != null}">
                        <h:outputText value="#{bundle.ViewRepresentanteLabel_idRepresentante}"/>
                        <h:outputText value="#{representanteController.selected.idRepresentante}" title="#{bundle.ViewRepresentanteTitle_idRepresentante}"/>
                        <h:outputText value="#{bundle.ViewRepresentanteLabel_nombresRepres}"/>
                        <h:outputText value="#{representanteController.selected.nombresRepres}" title="#{bundle.ViewRepresentanteTitle_nombresRepres}"/>
                        <h:outputText value="#{bundle.ViewRepresentanteLabel_apellidosRepres}"/>
                        <h:outputText value="#{representanteController.selected.apellidosRepres}" title="#{bundle.ViewRepresentanteTitle_apellidosRepres}"/>
                        <h:outputText value="#{bundle.ViewRepresentanteLabel_edadRepres}"/>
                        <h:outputText value="#{representanteController.selected.edadRepres}" title="#{bundle.ViewRepresentanteTitle_edadRepres}"/>
                        <h:outputText value="#{bundle.ViewRepresentanteLabel_parentesco}"/>
                        <h:outputText value="#{representanteController.selected.parentesco}" title="#{bundle.ViewRepresentanteTitle_parentesco}"/>
                        <h:outputText value="#{bundle.ViewRepresentanteLabel_telefono}"/>
                        <h:outputText value="#{representanteController.selected.telefono}" title="#{bundle.ViewRepresentanteTitle_telefono}"/>
                        <h:outputText value="#{bundle.ViewRepresentanteLabel_idAlumno}"/>
                        <h:outputText value="#{representanteController.selected.idAlumno}" title="#{bundle.ViewRepresentanteTitle_idAlumno}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="RepresentanteViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>